# Generated by Django 5.2.14 on 2026-05-27 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=50)),
                ('co2e', models.FloatField(default=0)),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('review', 'Review'), ('approved', 'Approved')], default='review', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawrecord')),
            ],
        ),
    ]
