# Generated by Django 5.2.14 on 2026-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
