# Generated by Django 5.2.14 on 2026-05-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_emissionrecord_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='review', max_length=20),
        ),
    ]
